server:
  port: 8412

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz
    username: root
    password: nj30103
    driver-class-name: com.mysql.cj.jdbc.Driver
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: myScheduler
          threadPool:
            threadCount: 5
    job-store-type: jdbc
    jdbc:
#      url: jdbc:mysql://localhost:3306/quartz
#      username: root
#      password: nj30103
#      driver-class-name: com.mysql.cj.jdbc.Driver
      initialize-schema: never
